name: Sync from Gitee

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Set up Git
      run: |
        git config user.name "Lucas04-nhr"
        git config user.email "lucas04@foxmail.com"

    - name: Set Git Configuration
      run: |
        git config pull.rebase false

    - name: Pull from Gitee
      run: |
        git remote add gitee https://gitee.com/haanxuan/GT-Manual.git
        git fetch gitee  # Assuming 'main' is your default branch, change it if needed
        git merge -X theirs --allow-unrelated-histories --no-ff gitee/master
        
    - name: Configure SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Push to GitHub
      run: |
        git push origin main  # Assuming 'main' is your default branch, change it if needed
